Repository killer0071234/python-zamg, pull requests merged in 2022-12, with the labels that each got.

#98 Fix wrong time format
  src/zamg/zamg.py
  tests/data_metadata.json
  tests/data_station.json
  tests/test_zamg.py
Labels: bug

#109 Add version info to http header
  src/zamg/__init__.py
  src/zamg/zamg.py
Labels: enhancement

#110 Update version to 0.2.2
  package.json
  pyproject.toml
Labels: dependencies
