Repository killer0071234/python-zamg, pull requests merged in 2023-09, with the labels that each got.

#215 Bump python from 3.9 to 3.11
  .github/workflows/python-publish.yml
  .github/workflows/tests.yaml
  Dockerfile.dev
  pyproject.toml
  requirements.txt
  src/zamg/__init__.py
Labels: dependencies, python

#211 Update domain to geosphere.at
  README.md
  src/zamg/zamg.py
  tests/test_zamg.py
Labels: enhancement, testing

#224 Publish PyPI package with OIDC
  .github/workflows/python-publish.yml
Labels: build
